"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

from .environment import get_django_secret_key, is_production_environment

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Production reads this value from a protected environment setting. Local
# development uses an explicitly non-production fallback from the helper.
SECRET_KEY = get_django_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'omnilab-bk8q.onrender.com',
    '127.0.0.1',
    'localhost',
]

# Render terminates HTTPS before forwarding requests to Django. Trust its
# forwarded protocol only in production so SecurityMiddleware recognizes the
# original HTTPS request and does not redirect it back through the proxy.
IS_PRODUCTION_ENVIRONMENT = is_production_environment()
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https")
    if IS_PRODUCTION_ENVIRONMENT
    else None
)
SECURE_SSL_REDIRECT = IS_PRODUCTION_ENVIRONMENT
SESSION_COOKIE_SECURE = IS_PRODUCTION_ENVIRONMENT
CSRF_COOKIE_SECURE = IS_PRODUCTION_ENVIRONMENT

# Start with a one-hour HSTS window. Keep subdomains and preload disabled until
# the production proxy behavior has a longer observation history. Silence only
# the two deployment warnings that recommend those intentionally deferred
# HSTS extensions.
SECURE_HSTS_SECONDS = 3600 if IS_PRODUCTION_ENVIRONMENT else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SILENCED_SYSTEM_CHECKS = (
    ["security.W005", "security.W021"]
    if IS_PRODUCTION_ENVIRONMENT
    else []
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "omnilab",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
WHITENOISE_USE_FINDERS = True

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Keep the reaction endpoint available to a typical shared classroom
# while bounding automated traffic from one network address.
OMNILAB_REACTION_RATE_LIMIT_REQUESTS = int(
    os.getenv("OMNILAB_REACTION_RATE_LIMIT_REQUESTS", "60")
)
OMNILAB_REACTION_RATE_LIMIT_WINDOW_SECONDS = int(
    os.getenv("OMNILAB_REACTION_RATE_LIMIT_WINDOW_SECONDS", "600")
)

# Contact messages use Django's standard SMTP backend. Production supplies
# provider details through environment variables; no message content is logged
# or stored in the application database.
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("OMNILAB_EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("OMNILAB_EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("OMNILAB_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("OMNILAB_EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("OMNILAB_EMAIL_USE_TLS", "true").lower() == "true"
EMAIL_USE_SSL = os.getenv("OMNILAB_EMAIL_USE_SSL", "false").lower() == "true"
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise ImproperlyConfigured(
        "OMNILAB_EMAIL_USE_TLS and OMNILAB_EMAIL_USE_SSL cannot both be true."
    )
EMAIL_TIMEOUT = min(
    max(int(os.getenv("OMNILAB_EMAIL_TIMEOUT", "8")), 1),
    8,
)
DEFAULT_FROM_EMAIL = os.getenv(
    "OMNILAB_CONTACT_FROM_EMAIL",
    "omnilab-bk8q@mail.tin.computer",
)
OMNILAB_CONTACT_RATE_LIMIT_REQUESTS = int(
    os.getenv("OMNILAB_CONTACT_RATE_LIMIT_REQUESTS", "5")
)
OMNILAB_CONTACT_RATE_LIMIT_WINDOW_SECONDS = int(
    os.getenv("OMNILAB_CONTACT_RATE_LIMIT_WINDOW_SECONDS", "3600")
)
